#!/usr/bin/env bash
exec > /tmp/part-001.log 2>&1
set -eu
pwd
whoami
export HOME=/root
sudo amazon-linux-extras install -y ruby2.6
sudo yum install -y @"Development Tools"
sudo yum install -y ruby-devel libxml2 libxml2-devel libxslt libxslt-devel patch redhat-rpm-config sqlite-devel
curl -sL https://rpm.nodesource.com/setup_12.x | sudo -E bash -
sudo yum install -y nodejs npm
curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
sudo yum install yarn -y
gem install bundler
gem install rails --version 5.2.4
cd /root
rails new --skip-spring example
cd example
bundle install
bundle install --path vendor/cache
bundle exec rails server --binding 0.0.0.0 --port 3000 &
wget -qO- http://localhost:3000
